name: beta

on:
  push:
    tags:
      - "beta"

jobs:
  build-and-release-beta:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    # NOTE: github.run_number increments for each run of the workflow. Therefore, you can have v0.9.11-beta.1 followed by v0.9.12-beta.2
    - run: Write-Output VERSION="$(([Xml] (Get-Content .\src\workspacer\workspacer.csproj)).Project.PropertyGroup.Version)-beta.$(${{ github.run_number }})" >> $env:GITHUB_ENV
    - name: Restore solution
      run: dotnet restore
    - name: Build
      run: dotnet publish /p:DefineConstants=BRANCH_beta /p:Version=$env:VERSION --configuration Release --no-restore
    - uses: actions/upload-artifact@v2
      with:
        name: workspacer-build
        path: .\src\workspacer\bin\Release\net5.0-windows\win10-x64\publish\
    - name: Publish installer
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop install wixtoolset
        .\scripts\buildinstaller.ps1 -buildDir .\src\workspacer\bin\Release\net5.0-windows\win10-x64\publish\ -version $env:VERSION
    - uses: actions/upload-artifact@v2
      with:
        name: workspacer-installer
        path: .\out\workspacer-${{ env.VERSION }}.msi
    - name: Zip build output
      run: Compress-Archive -Path .\src\workspacer\bin\Release\net5.0-windows\win10-x64\publish\* -DestinationPath ".\out\workspacer-$env:VERSION.zip"
    - uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
       delete_release: true
       tag_name: beta
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: ${{ env.VERSION }}
        title: workspacer ${{ env.VERSION }}
        prerelease: true
        files: |
          out/workspacer-${{ env.VERSION }}.zip
          out/workspacer-${{ env.VERSION }}.msi
